// apps/web/src/components/RemoteCursorsLayer.tsx
import { memo } from "react";
import { MousePointer2 } from "lucide-react";
import type { RemoteCursor } from "../hooks/useRemoteCursors";
import { participantColor } from "../utils/participant";
import styles from "./PuzzleBoard.module.css";

type Props = {
  cursors: RemoteCursor[];
  activeIds: Set<string>;
};

export const RemoteCursorsLayer = memo(function RemoteCursorsLayer({ cursors, activeIds }: Props) {
  return (
    <>
      {cursors.map((cursor) => (
        <div
          key={cursor.participantId}
          className={`${styles.remoteCursor}${activeIds.has(cursor.participantId) ? ` ${styles.dragging}` : ""}`}
          style={{
            "--cursor-x": `${cursor.x}px`,
            "--cursor-y": `${cursor.y}px`,
            "--cursor-color": participantColor(cursor.participantId),
          } as React.CSSProperties & Record<"--cursor-x" | "--cursor-y" | "--cursor-color", string>}
          title={cursor.name}
        >
          <MousePointer2 size={16} />
          <span>{cursor.name}</span>
        </div>
      ))}
    </>
  );
});

// apps/web/src/components/remote-cursors-layer.tsx
import { For } from "solid-js";
import { MousePointer2 } from "lucide-solid";
import type { RemoteCursor } from "../hooks/use-remote-cursors";
import { participantColor } from "../utils/participant";
import { cursorDragging, remoteCursor } from "./puzzle-board.styles";

type Props = {
  cursors: RemoteCursor[];
  activeIds: Set<string>;
};

export function RemoteCursorsLayer(props: Props) {
  return (
    <For each={props.cursors}>
      {(cursor) => (
        <div
          class={`${remoteCursor}${props.activeIds.has(cursor.participantId) ? ` ${cursorDragging}` : ""}`}
          style={{
            "--cursor-x": `${cursor.x}px`,
            "--cursor-y": `${cursor.y}px`,
            "--cursor-color": participantColor(cursor.participantId),
          }}
          title={cursor.name}
        >
          <MousePointer2 size={16} />
          <span>{cursor.name}</span>
        </div>
      )}
    </For>
  );
}
